const ATTR = { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" };

export function escapeAttr(value) {
  return String(value ?? "").replace(/[&<>"]/g, (ch) => ATTR[ch]);
}

export function isImageQuestion(q) {
  return q.presentation === "image";
}

export function choiceLetters(q) {
  return (q.choices ?? []).map((c) => c.label);
}

function imagesHtml(paths, alt) {
  return (paths ?? [])
    .map((src) => `<img src="${escapeAttr(src)}" alt="${escapeAttr(alt)}" loading="lazy">`)
    .join("");
}

export function stemHtml(q) {
  // Reading HTML is generated by our own extractor, never user input.
  return isImageQuestion(q) ? imagesHtml(q.stem.images, "Question") : q.stem.html ?? "";
}

export function choiceHtml(q, label) {
  const choice = (q.choices ?? []).find((c) => c.label === label);
  if (!choice) return "";
  return isImageQuestion(q) ? imagesHtml(choice.images, `Choice ${label}`) : choice.html ?? "";
}

export function rationaleHtml(q) {
  const rationale = q.rationale ?? {};
  if (rationale.images) return imagesHtml(rationale.images, "Explanation");
  return rationale.html ?? "";
}
