const ATTR = { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" };

export function escapeAttr(value) {
  return String(value ?? "").replace(/[&<>"]/g, (ch) => ATTR[ch]);
}

export function isImageQuestion(q) {
  return q.presentation === "image";
}

const PDFS = { math: "Math SAT Questions.pdf", reading: "SAT Reading.pdf" };

// Hosted PDFs live as GitHub release assets. The release URL serves them with
// Content-Type: application/pdf, so the browser's native viewer honours the
// #page= fragment the way a local file does.
const PDF_BASE = "https://github.com/shivanshpayak/SAT-Questions/releases/download/pdfs-v1";

// Where a question came from, so a bad crop can be checked against the original.
// Stored pages are 0-based mupdf indices; a viewer's #page= counts from 1.
export function sourceUrl(q) {
  const file = PDFS[q?.subject];
  const first = q?.source?.pages?.[0];
  if (!file || !Number.isInteger(first)) return null;
  const page = first + 1;
  return { href: `${PDF_BASE}/${encodeURIComponent(file)}#page=${page}`, page };
}

export function choiceLetters(q) {
  return (q.choices ?? []).map((c) => c.label);
}

function imagesHtml(paths, alt) {
  return (paths ?? [])
    .map((src) => `<img src="${escapeAttr(src)}" alt="${escapeAttr(alt)}" loading="lazy">`)
    .join("");
}

export function stemHtml(q) {
  // Reading HTML is generated by our own extractor, never user input.
  return isImageQuestion(q) ? imagesHtml(q.stem.images, "Question") : q.stem.html ?? "";
}

export function choiceHtml(q, label) {
  const choice = (q.choices ?? []).find((c) => c.label === label);
  if (!choice) return "";
  return isImageQuestion(q) ? imagesHtml(choice.images, `Choice ${label}`) : choice.html ?? "";
}

export function rationaleHtml(q) {
  const rationale = q.rationale ?? {};
  if (rationale.images) return imagesHtml(rationale.images, "Explanation");
  return rationale.html ?? "";
}
